### ISSUE TITLE
Broken idevicelocation - Invalid Service?

### ISSUE THREAD

**Issue by huming2207** [jkcoxson/rusty_libimobiledevice#21]
Hi @jkcoxson 

Firstly thanks for your efforts on this project. 

I had a try on compiling the sample command line tools with latest commit (https://github.com/jkcoxson/rusty_libimobiledevice/commit/8d5519fb784b73107c99ac10fdee1f1d0189fb93) and I've got this compliation error:

```
error[E0308]: mismatched types
   --> src/idevicelocation.rs:149:32
    |
149 |             match service.send(lat_len) {
    |                           ---- ^^^^^^^ expected `Vec<u8>`, found `Vec<i8>`
    |                           |
    |                           arguments to this method are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `Vec<i8>`
note: method defined here
   --> /Users/hu/Projects/rusty_libimobiledevice/src/service.rs:89:12
    |
89  |     pub fn send(&self, data: Vec<u8>) -> Result<u32, ServiceError> {
    |            ^^^^

error[E0308]: mismatched types
   --> src/idevicelocation.rs:162:32
    |
162 |             match service.send(latitude) {
    |                           ---- ^^^^^^^^ expected `Vec<u8>`, found `Vec<i8>`
    |                           |
    |                           arguments to this method are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `Vec<i8>`
note: method defined here
   --> /Users/hu/Projects/rusty_libimobiledevice/src/service.rs:89:12
    |
89  |     pub fn send(&self, data: Vec<u8>) -> Result<u32, ServiceError> {
    |            ^^^^

error[E0308]: mismatched types
   --> src/idevicelocation.rs:177:32
    |
177 |             match service.send(lon_len) {
    |                           ---- ^^^^^^^ expected `Vec<u8>`, found `Vec<i8>`
    |                           |
    |                           arguments to this method are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `Vec<i8>`
note: method defined here
   --> /Users/hu/Projects/rusty_libimobiledevice/src/service.rs:89:12
    |
89  |     pub fn send(&self, data: Vec<u8>) -> Result<u32, ServiceError> {
    |            ^^^^

error[E0308]: mismatched types
   --> src/idevicelocation.rs:190:32
    |
190 |             match service.send(longitude) {
    |                           ---- ^^^^^^^^^ expected `Vec<u8>`, found `Vec<i8>`
    |                           |
    |                           arguments to this method are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `Vec<i8>`
note: method defined here
   --> /Users/hu/Projects/rusty_libimobiledevice/src/service.rs:89:12
    |
89  |     pub fn send(&self, data: Vec<u8>) -> Result<u32, ServiceError> {
    |            ^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `examples` (bin "idevicelocation") due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

Apparently this is just a simple type error. I changed the `Vec<i8>` to `Vec<u8>` accordingly and it gets compiled. 

Then I run the program, for example `./idevicelocation -u 0000XXXX-XXXXXXXXXX start -37.8136 144.9631` it returned me `Unable to start service: InvalidService`. 

Do you have any idea? I guess it might be the same issue like this: https://github.com/libimobiledevice/libimobiledevice/issues/1553

If that's the case then I think maybe we have to wait for upstream to fix their issue first...

Regards,
Jackson

**Comment by jkcoxson** [comment]
Hey Jackson
For the i8 vs u8 issue, what platform are you building for? That's interesting, and probably a regression from removing the c_chars from the returns. I'll look into it when I have the chance.

As for the unknown service, are you on iOS 17 or up? I know many of the services that used to be accessible via lock down (which this library uses) are no longer there. I've been out of the loop for the past 2 years on my mission, but I would like to implement the new protocol in this library.

In the mean time, pymobiledevice3 has support.

Best regards,
Also Jackson

**Comment by huming2207** [comment]
Hi @jkcoxson 

Thanks for your reply!

> As for the unknown service, are you on iOS 17 or up? I know many of the services that used to be accessible via lock down (which this library uses) are no longer there. I've been out of the loop for the past 2 years on my mission, but I would like to implement the new protocol in this library.

Ah yes, I'm on iOS 18. I think that's the main issue. 😅

I will close this issue for now as this is (sort of) the upstream's matter. You may re-open this again later if you would like to. 

Regards,
Jackson
